<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Default suite has started execution]]>
    </line>
    <line>
      <![CDATA[addAddressTest test script execution started]]>
    </line>
    <line>
      <![CDATA[addAddressTest test script failed and captured the screenshot]]>
    </line>
  </reporter-output>
  <suite started-at="2024-06-02T15:08:23 IST" name="Default suite" finished-at="2024-06-02T15:08:51 IST" duration-ms="28098">
    <groups>
    </groups>
    <test started-at="2024-06-02T15:08:23 IST" name="Default test" finished-at="2024-06-02T15:08:51 IST" duration-ms="28098">
      <class name="demo.AddAddressTest">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:demo.AddAddressTest@1573f9fc]" started-at="2024-06-02T15:08:23 IST" name="openBrowser" finished-at="2024-06-02T15:08:33 IST" duration-ms="9514" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:demo.AddAddressTest@1573f9fc]" started-at="2024-06-02T15:08:33 IST" name="login" finished-at="2024-06-02T15:08:39 IST" duration-ms="5711" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="addAddressTest()[pri:0, instance:demo.AddAddressTest@1573f9fc]" started-at="2024-06-02T15:08:39 IST" name="addAddressTest" finished-at="2024-06-02T15:08:39 IST" duration-ms="63" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at demo.AddAddressTest.addAddressTest(AddAddressTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addAddressTest test script execution started]]>
            </line>
            <line>
              <![CDATA[addAddressTest test script failed and captured the screenshot]]>
            </line>
          </reporter-output>
        </test-method> <!-- addAddressTest -->
        <test-method is-config="true" signature="logout()[pri:0, instance:demo.AddAddressTest@1573f9fc]" started-at="2024-06-02T15:08:50 IST" name="logout" finished-at="2024-06-02T15:08:51 IST" duration-ms="978" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:demo.AddAddressTest@1573f9fc]" started-at="2024-06-02T15:08:51 IST" name="closeBrowser" finished-at="2024-06-02T15:08:51 IST" duration-ms="278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- demo.AddAddressTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
